# Generated by Django 4.2.4 on 2023-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_isbn_book_isbn_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
